version: 2
jobs: 
  build: 
    working_directory: ~/DockerComposeCI # set working directory from which you want to run the tests
    docker:
      - image: cimg/node:16.14.2 # this image is specifically required to run node apps on circle ci
    steps:
      - checkout
      - setup_remote_docker:    # need this to run docker-compose on remote for this build
          version: 20.10.7     # add the version number according to the version on local
          docker_layer_caching: true   # to save excessive docker layer pulls set this to true
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:    
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: run-test
          command: |
            docker-compose up -d
            cd NodeMongoDockerApp
            npm run test