version: 2
jobs: 
  build: 
    working_directory: ~/DockerComposeCI/NodeMongoDockerApp
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: run-test
          command: npm run test